Develop
acme101/dev-setup pull request #1
Opened 2017-08-02 11:24 UTC by duc4nh

- Update README
- Not sure why in develop branch the vagrant_config_override.example.json was removed so I readd it, since it is still be mentioned in README

2017-08-02 11:26 UTC, hoatle commented
@duc4nh that's new feature from teracy-dev v0.5.0-c1, we're going to use https://github.com/acme101/dev-setup/blob/develop/vagrant_config_default.json instead.

2017-08-02 11:27 UTC, hoatle requested changes

2017-08-02 11:27 UTC, hoatle commented on README.md
>      $ cp workspace/dev-setup/vagrant_config_override.example.json vagrant_config_override.json
remove this

2017-08-02 11:27 UTC, hoatle commented on vagrant_config_override.example.json
> +{
remove this file

2017-08-02 11:37 UTC, duc4nh commented
Ok, let me update the readme instead. It still mention `cp workspace/dev-setup/vagrant_config_override.example.json vagrant_config_override.json`

2017-08-02 12:08 UTC, duc4nh commented
does this file vagrant_config_default.json work just by putting it at teracy-dev root? or a rename needed?

2017-08-02 12:16 UTC, hoatle commented
workspace/dev-setup/vagrant_config_default.json is auto discovered by teracy-dev, users don't have to do anything.

For each vagrant_config_default.json, users can create vagrant_config_override.json files themselves when they want to custom anything for their usage. However, in most cases, default configs are enough.

2017-08-02 12:17 UTC, hoatle commented
@duc4nh see more: https://github.com/teracyhq/dev/issues/315

2017-08-03 04:04 UTC, duc4nh commented
requested changes applied

2017-08-03 04:05 UTC, hoatle approved these changes
LGTM

2017-08-03 04:05 UTC, merged