@ #2 | should add kubernetes-stack-cookbook
acme101/dev-setup pull request #3
Opened 2017-08-17 05:17 UTC by duc4nh

connect #2

2017-08-17 05:23 UTC, hoatle commented
@duc4nh see my comment here https://github.com/acme101/dev-setup/issues/2#issuecomment-322971790

2017-08-17 05:24 UTC, hoatle requested changes
need to update with the updated json config

2017-08-17 05:45 UTC, duc4nh commented
json config updated

2017-08-17 05:49 UTC, hoatle requested changes

2017-08-17 05:49 UTC, hoatle commented on chef/main-cookbooks/acme/recipes/k8s.rb
> +    # fix gsutil temporarily
this is not required anymore, fixed by k8s-stack-cookbook

2017-08-17 05:49 UTC, hoatle commented on chef/main-cookbooks/acme/recipes/k8s.rb
> +#
please add support for "install" or "remove" action, refer here: https://github.com/iorad/dev-setup/pull/18

2017-08-18 01:14 UTC, duc4nh commented on chef/main-cookbooks/acme/recipes/k8s.rb
> +#
updated

2017-08-18 01:40 UTC, hoatle commented on chef/docker-compose.yml
> +    image: chef/chefdk
use teracy/chefdk image instead

2017-08-19 09:43 UTC, hoatle commented
@duc4nh please update to use teracy/chefdk image instead of chef/chefdk

2017-08-19 11:05 UTC, duc4nh commented
updated to use teracy/chefdk

2017-08-19 11:32 UTC, hoatle approved these changes
LGTM

2017-08-19 11:32 UTC, merged